# Generated by Django 5.0.1 on 2024-01-26 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
    ]
